### ISSUE TITLE
unofficial roadmap?

### ISSUE THREAD

**Issue by ohnx** [ohnx-osdev/BareMetal-kernel#1]
- [ ] Complete IPv4-stack, ARP, UDP, TCP, ICMP and DHCP
- [ ] C and Newlib
- [ ] Port libDraw to assembly, then integrate into kernel
- [ ] nVidia or AMD drivers
- [ ] ext4 or fat32 fs instead of bmfs
- [ ] Modular OS - allow selection of different modules (ie, graphics, network, fs)
